[tool.poetry]
name = "poc-champ"
version = "0.1.0"
description = ""
authors = ["crudenesss <osbochok.w@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"
requests = "^2.32.3"
bs4 = "^0.0.2"
lxml = "^5.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
