[tool.poetry]
name = "poc-champ"
version = "1.1.0"
description = ""
authors = ["crudenesss <osbochok.w@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
bs4 = "^0.0.2"
selenium = "^4.25.0"
art = "^6.3"
lxml = "^6.1.1"
rich = "^15.0.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.8"
black = "^25.1.0"
pytest = "^8.4.2"

[tool.poetry.scripts]
poc-champ = "poc_champ.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
